config/routes.rb
Rails.application.routes.draw do
  resources :enquiries

  root 'pages#home'

  get 'pages/contact'

  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
         devise devise :omniauthable, :omniauth_providers => [:google_oauth2]     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    respond_to do |format|
      if @enquiry.save
        EnquiryMailer.response(@enquiry).deliver_now
        EnquiryMailer.received(@enquiry).deliver_now
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render :show, status: :created, location: @enquiry }
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    respond_to do |format|
      if @enquiry.update(enquiry_params)
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @enquiry }
      else
        format.html { render :edit }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :subject, :message)
    end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def login
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
    @email=Email.new
  end

  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/enquiries/_form.html.erb
<div class="backgroundcolor">

    <%= simple_form_for(@enquiry) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :subject %>
        <%= f.input :message %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
        <%= link_to 'Home', root_path %>
      </div>
    <% end %>

</div>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |

<%= link_to 'Home', root_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.name %></td>
        <td><%= enquiry.email %></td>
        <td><%= enquiry.subject %></td>
        <td><%= enquiry.message %></td>
        <td><%= link_to 'Show', enquiry %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>


<%= link_to 'Back', root_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enquiry.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @enquiry.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @enquiry.message %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |

<%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio2</title>
    <meta charset="utf-8">
    <meta name="description" content="Tristan Southwell's Portfolio">
    <meta name="author" content ="Tristan Southwell">
    <meta name="keyword" content ="Full-Stack Web Developer">
    <!-- <meta http-equiv="refresh" content ="120"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- facebook metas -->
    <meta property="og:url" content="http://tristansouthwell.com">
    <meta property="og:image" content="{{imageUrl}}">
    <meta property="og:description" content="Full-Stack Web Developer">
    <meta property="og:title" content="Tristan Southwell's Portfolio">
    <meta property="og:site_name" content="Tristan Southwell's Portfolio">
<!-- twitter metas -->
    <meta name="twitter:card" content="Tristan Southwell's Portfolio">
    <meta name="twitter:url" content="http://tristansouthwell.com">
    <meta name="twitter:title" content="Tristan Southwell's Portfolio">
    <meta name="twitter:description" content="Full-Stack Web Developer">
    <meta name="twitter:image" content="{{imageUrl}}">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

<div id="container">
  <div id="group1">
    <div class="background">
      <div id="header_text">
          <div class="head">
            <h1>TRISTAN SOUTHWELL</h1>
            <h2>Full Stack web developer and extraordinary human being</h2>
          </div>
      </div>
    </div>

    <div class="foreground">
      <div id="portfolio">
          <div class="middle">
              <h1>COOL STUFF I HAVE DONE</h1>
          </div>
          <div class="row">
              <% 4.times do %>
                  <div class="thumbnail">
                      <img src="http://placehold.it/242x200/333333/999999" class="img-responsive center-block" alt="placeholder">
                  </div>
              <% end %>
          </div>
      </div>

<footer class="footer">
  <div class="aboutmecolor">
    <div class="row">
      <!-- <div class="picme"> -->
      <div class="col-md-6 picme">
          <img src='http://res.cloudinary.com/ddpizrmrj/image/upload/v1472795072/FullSizeRender_copy_lnyney.png'>
      </div>
      <!-- </div> -->

    <div class="row" style="">
      
        <div class="aboutme">
          <div class="col-md-6">
            <h1>I am Tristan Southwell<h1>
            <h3>Probably the best web developer I know<h3>
            <p>Splitting my time between Sydney and Wollongong NSW.  I get the best of both worlds.  The buzz and the opportunity of the city, and the quiet and relaxation of the country.<br>
              In my spare time I enjoy the great outdoors.  I scuba dive, spearfish, bush walk, and kayak.
              Discovering code was a huge discovery in my life.  My high school woodwork teacher used to call me ‘Lightening’ because I could not hammer in a  nail.  With code I have found something that allows me to build and create without having to pick up a hammer or a nail.
              <br>In my previous life I was an Accounting and Finance professional.  I have left that life behind and am now a Full Stack web developer.  I specialise in Ruby on Rails, Node.js,  Angular.js, and React.js and I want to build things for you.
            </p>

          </div>
        </div>
    </div>
  </div>
    <div class="footercolor">
      <div class="row" style="height: 300px;">
      <div class="bottom">
        <div class="bottomfont">
          <div class="col-md-6">
            <p>
              If you like what I do, have something you would like me to work on, or just want to say hi send me an email.  Dont be shy.
            </p>
          </div>
          <div class="col-md-6">
            <p>Feel free to contact me, or check out me and my work via the links below</p>
        </div>
          <p>
          <div class="social">
            <ul>
              <li>
                <a href='https://github.com/Unsentletter'>
                <i class="fa fa-lg fa-github"></i>
                </a>
              </li>
              <li>
                <a href='https://www.linkedin.com/in/tristan-southwell-716681a3?trk=nav_responsive_tab_profile'>
                <i class="fa fa-lg fa-linkedin"></i>
                </a>
              </li>
              <li>
                <a>
                <%= link_to new_enquiry_path do %>
                <i class="fa fa-lg fa-envelope"></i>
                <%end%>
                </a>
              </li>
              <li>
                <%=link_to 'tristan@tristansouthwell.com',new_enquiry_path%>
              </li>
            </ul>
          </div>
          </p>
        </div>
      </div>
    </footer>
  </div>
</div>
</div>